In [1]:
import pandas as pd
import matplotlib.pyplot as plt
df1 = pd.read_csv('train.csv')

In [2]:
df1.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,id,estimated_check_in_duration,booking_difficulty_score
0,Resort Hotel,0,NaN,9,March,2017,2,0.820075,2.546977,1,...,0,Check-Out,2017-03-06,Edward Davis,EDavis@mail.com,129-327-5067,************1227,33852,NaN,NaN
1,City Hotel,0,82.916916,11,March,2017,15,-0.325630,2.002309,2,...,2,Check-Out,2017-03-16,Joshua Sullivan,JSullivan@zoho.com,748-584-5256,************7930,97750,47.282901,-3.218666
2,City Hotel,0,24.534646,44,October,2016,23,1.820523,1.289780,1,...,1,Check-Out,2016-10-25,Zachary Bishop,Bishop_Zachary@gmail.com,880-124-3628,************2924,100248,13.811002,3.859197
3,City Hotel,1,169.265992,12,March,2017,23,0.721699,1.848563,2,...,2,Canceled,2017-01-19,Victoria Kent,Victoria.Kent@aol.com,814-180-1532,************7923,65077,81.319112,1.510322
4,City Hotel,0,-22.240921,3,Veganuary,2017,19,-0.097702,1.045354,2,...,1,Canceled,2016-10-26,Michael Johnson,Johnson_Michael11@xfinity.com,118-263-8905,************9630,62714,-9.889995,4.345359

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83573 entries, 0 to 83572
Data columns (total 39 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           83573 non-null  object
 1   is_canceled                     83573 non-null  int64
 2   lead_time                       79290 non-null  float64
 3   arrival_date_year               83573 non-null  int64
 4   arrival_date_month              83573 non-null  object
 5   arrival_date_week_number        83573 non-null  int64
 6   arrival_date_day_of_month       83573 non-null  int64
 7   stays_in_weekend_nights         83573 non-null  float64
 8   stays_in_week_nights            83573 non-null  float64
 9   adults                          83573 non-null  int64
 10  children                        83571 non-null  float64
 11  babies                          83573 non-null  int64
 12  meal                            79290 non-null  object
 13  country                         79033 non-null  object
 14  market_segment                  83573 non-null  object
 15  distribution_channel            83573 non-null  object
 16  is_repeated_guest               83573 non-null  int64
 17  previous_cancellations          83573 non-null  int64
 18  previous_bookings_not_canceled  83573 non-null  int64
 19  reserved_room_type              83573 non-null  object
 20  assigned_room_type              83573 non-null  object
 21  booking_changes                 83573 non-null  int64
 22  deposit_type                    83573 non-null  object
 23  agent                           72224 non-null  float64
 24  company                         4674 non-null   float64
 25  days_in_waiting_list            83573 non-null  float64
 26  customer_type                   83573 non-null  object
 27  adr                             79290 non-null  float64
 28  required_car_parking_spaces     83573 non-null  int64
 29  total_of_special_requests       83573 non-null  int64
 30  reservation_status              83573 non-null  object
 31  reservation_status_date         83573 non-null  object
 32  name                            83573 non-null  object
 33  email                           83573 non-null  object
 34  phone-number                    83573 non-null  object
 35  credit_card                     83573 non-null  object
 36  id                              83573 non-null  int64
 37  estimated_check_in_duration     79290 non-null  float64
 38  booking_difficulty_score        79290 non-null  float64
dtypes: float64(10), int64(13), object(16)
memory usage: 24.9+ MB

In [4]:
df1.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,id,estimated_check_in_duration,booking_difficulty_score
count,83573.000000,79290.000000,83573.000000,83573.000000,83573.000000,83573.000000,83573.000000,83573.000000,83571.000000,83573.000000,...,83573.000000,72224.000000,4674.000000,83573.000000,79290.000000,83573.000000,83573.000000,83573.000000,79290.000000,79290.000000
mean,0.397210,103.379569,27.120326,2016.155912,15.788077,0.928752,2.492898,1.859225,0.102918,0.008137,...,0.220681,86.603774,186.998074,2.321765,101.735184,0.061790,0.572745,59698.368983,51.673768,1.293816
std,0.489323,119.376604,13.619669,0.707381,8.782488,1.118739,2.126703,0.594781,0.397277,0.096017,...,0.654785,110.672677,130.511313,19.326393,57.456359,0.243445,0.794273,34498.851794,60.534659,2.294587
min,0.000000,-227.156938,1.000000,2015.000000,1.000000,-1.791310,-3.794357,0.000000,0.000000,0.000000,...,0.000000,1.000000,9.000000,-36.442446,-80.136040,0.000000,0.000000,1.000000,-123.491940,-5.127325
25%,0.000000,18.369438,16.000000,2016.000000,8.000000,0.065392,1.105973,2.000000,0.000000,0.000000,...,0.000000,9.000000,59.000000,-5.701373,65.609982,0.000000,0.000000,29788.000000,8.512819,0.103028
50%,0.000000,79.567680,27.000000,2016.000000,16.000000,0.795712,2.217654,2.000000,0.000000,0.000000,...,0.000000,14.000000,174.000000,0.394790,96.152208,0.000000,0.000000,59782.000000,40.426761,1.090596
75%,1.000000,167.570697,38.000000,2017.000000,23.000000,1.713242,3.551786,2.000000,0.000000,0.000000,...,0.000000,229.000000,268.000000,6.589958,131.647735,0.000000,1.000000,89525.000000,84.541252,2.131485
max,1.000000,741.651834,53.000000,2017.000000,31.000000,19.232182,49.354003,55.000000,10.000000,9.000000,...,20.000000,535.000000,543.000000,401.792112,5411.546686,8.000000,5.000000,119390.000000,370.155876,55.593803

In [5]:
df1.isnull().sum()

hotel                                 0
is_canceled                           0
lead_time                          4283
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              2
babies                                0
meal                               4283
country                            4540
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             11349
company                           78899
days_in_waiting_list                  0
customer_type                         0
adr                                4283
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
name                                  0
email                                 0
phone-number                          0
credit_card                           0
id                                    0
estimated_check_in_duration        4283
booking_difficulty_score           4283
dtype: int64

In [6]:
# get a list of the columns
col_list = list(df1)
# use this handy way to swap the elements
col_list[3], col_list[5] = col_list[5], col_list[3]
# assign back, the order will now be swapped
df1.columns = col_list

In [7]:
df1.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,arrival_date_month,arrival_date_year,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,id,estimated_check_in_duration,booking_difficulty_score
0,Resort Hotel,0,NaN,9,March,2017,2,0.820075,2.546977,1,...,0,Check-Out,2017-03-06,Edward Davis,EDavis@mail.com,129-327-5067,************1227,33852,NaN,NaN
1,City Hotel,0,82.916916,11,March,2017,15,-0.325630,2.002309,2,...,2,Check-Out,2017-03-16,Joshua Sullivan,JSullivan@zoho.com,748-584-5256,************7930,97750,47.282901,-3.218666
2,City Hotel,0,24.534646,44,October,2016,23,1.820523,1.289780,1,...,1,Check-Out,2016-10-25,Zachary Bishop,Bishop_Zachary@gmail.com,880-124-3628,************2924,100248,13.811002,3.859197
3,City Hotel,1,169.265992,12,March,2017,23,0.721699,1.848563,2,...,2,Canceled,2017-01-19,Victoria Kent,Victoria.Kent@aol.com,814-180-1532,************7923,65077,81.319112,1.510322
4,City Hotel,0,-22.240921,3,Veganuary,2017,19,-0.097702,1.045354,2,...,1,Canceled,2016-10-26,Michael Johnson,Johnson_Michael11@xfinity.com,118-263-8905,************9630,62714,-9.889995,4.345359

In [ ]:
#Converting typo 'Veganuary' to 'January'.
df1['arrival_date_month'].replace('Veganuary', 'January', inplace=True)

In [ ]:
#Converting all negative values in the lead_time column to positive and rounding them.
df1['lead_time'] = df1['lead_time'].abs()
df1['lead_time'] = df1['lead_time'].round()

In [12]:
#Converting all negative values in the stays_in_weekend_nights column and stays_in_week_nights to positive and rounding them.
df1['stays_in_weekend_nights'] = df1['stays_in_weekend_nights'].abs()
df1['stays_in_weekend_nights'] = df1['stays_in_weekend_nights'].round()

df1['stays_in_week_nights'] = df1['stays_in_week_nights'].abs()
df1['stays_in_week_nights'] = df1['stays_in_week_nights'].round()

In [13]:
# removing meal and country columns
df1 = df1.drop(['meal','country'], axis = 1, index=None)